# Generated by Django 3.0.6 on 2020-05-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, max_length=2083)),
                ('url', models.URLField(max_length=2083)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(blank=True, max_length=75)),
            ],
        ),
    ]
